# Generated by Django 4.1.3 on 2022-11-22 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('uid', models.UUIDField(editable=False, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='email')),
                ('fullname', models.CharField(max_length=50, verbose_name='full name')),
                ('date_of_birth', models.DateField(verbose_name='date of birth')),
                ('picture', models.ImageField(upload_to='profile_pic/', verbose_name='profile picture')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
