# Generated by Django 4.1.3 on 2022-11-22 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_remove_user_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pic/', verbose_name='profile picture'),
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
