# Generated by Django 4.0.3 on 2022-11-23 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_alter_user_uid_todo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(blank=True, default='6ef81dcd-d8ae-4fad-b29e-aa79fd5eae05', editable=False, unique=True),
        ),
    ]
