# Generated by Django 4.0.3 on 2022-11-23 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_alter_todo_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='user_id',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='todo',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='task',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(blank=True, default='7243f376-6027-4bc3-b112-61ba04674d72', editable=False, unique=True),
        ),
    ]
