# Generated by Django 4.0.3 on 2022-11-23 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_todo_user_id_alter_todo_description_alter_todo_task_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(blank=True, default='e3240970-fdf8-4831-bebe-f155040d5192', editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='user_id',
            field=models.CharField(editable=False, max_length=5),
        ),
    ]
