# Generated by Django 4.0.3 on 2022-11-23 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_alter_todo_uid_alter_todo_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('complete', 'complete'), ('overdue', 'overdue')], default=('pending', 'pending'), max_length=15),
        ),
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(blank=True, default='68476ea6-1d1a-4351-a948-7f744c56df76', editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='user_id',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
