# Generated by Django 4.0.3 on 2022-11-24 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_alter_todo_status_alter_todo_uid_alter_todo_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(blank=True, unique=True),
        ),
    ]
